# Site settings
title: Geometry and Dynamics of Neural Computation
email:
description: > # this means to ignore newlines until "baseurl:"
baseurl: "/dynamics-workshop" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

twitter_username:
github_username:

# Build settings
markdown: kramdown
